# Generated by Django 4.1.7 on 2023-06-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='pass1',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='pass1',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='pass2',
        ),
    ]
