# Generated by Django 4.1.7 on 2023-06-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_signin_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='mail',
            new_name='Username',
        ),
        migrations.AddField(
            model_name='signin',
            name='Login_Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='signin',
            name='Login_Time',
            field=models.TimeField(auto_now=True),
        ),
    ]
