# Generated by Django 4.1.7 on 2023-06-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_mail_signin_username_signin_login_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='Username',
            field=models.CharField(max_length=20),
        ),
    ]
