# Generated by Django 4.1.7 on 2023-06-03 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_signin_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='Login_Date',
        ),
        migrations.RemoveField(
            model_name='signin',
            name='Login_Time',
        ),
        migrations.AddField(
            model_name='signin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
