# Generated by Django 4.1.7 on 2023-06-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_signin_login_date_remove_signin_login_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
